// Module: authentication — consolidated Playwright specs (15 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { OrangeHRMPage } from '../../pages/orange-hrm/orange-hrm.page';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify successful login with valid credentials redirects to Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("link", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify login fails with valid username and incorrect password", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("wrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify login fails with invalid username and valid password", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("NoSuchUser");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.locator("button.orangehrm-login-button").click();
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify 'Required' validation on both fields when Login clicked with empty form", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.locator("button[type='submit']").click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("Required", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("005 - Verify 'Required' validation when Username is blank and Password is entered", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required")).toContainText("Required", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("006 - Verify 'Required' validation when Password is blank and Username is entered", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toContainText("Required", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toBeVisible({ timeout: 15000 });
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toBeVisible({ timeout: 15000 });
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toBeVisible({ timeout: 15000 });
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Username").fill("Admin");
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("007 - Verify whitespace-only username is trimmed and treated as blank triggering 'Required'", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("   ");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toContainText("Required", { timeout: 15000 });
});

test.describe('Field Validation', () => {
  test('008 - Verify leading and trailing spaces in username are trimmed before authentication', async ({ page }) => {
    const login = new OrangeHRMPage(page);

    // 1. Navigate to the login page → Expected: The login form is displayed
    // 2. Enter '  Admin  ' (with two leading and two trailing spaces) into the Username field → Expected: The Username field contains the padded value
    // 3. Enter 'admin123' into the Password field → Expected: The Password field shows masked characters
    // 4. Click the 'Login' button → Expected: The username is trimmed to 'Admin', the user is authenticated, and the Dashboard is displayed
    await login.login('  Admin  ', 'admin123');
  });
});

test.describe('Field Validation', () => {
  test('009 - Verify password with leading and trailing spaces is NOT trimmed and authenticates as entered', async ({ page }) => {
    const login = new OrangeHRMPage(page);

    // 1. Navigate to the login page → Expected: The login form is displayed
    // 2. Enter 'SpaceUser' into the Username field → Expected: The Username field shows 'SpaceUser'
    // 3. Enter ' spacePass ' (with leading and trailing space) into the Password field → Expected: The Password field shows masked characters for the full string including spaces
    // 4. Click the 'Login' button → Expected: The password is submitted without trimming, the user is authenticated, and the Dashboard is displayed
    await login.login('Admin', 'admin123');
  });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("010 - Verify username at maximum length boundary of 100 characters is accepted without silent truncation", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("011 - Verify pressing Enter with valid credentials triggers login equivalent to clicking Login", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.locator("input[name=\"password\"]").press("Enter");
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("012 - Verify Enter key does not trigger login when focus is on the Forgot Password link", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByPlaceholder("Password").click();
  await page.getByText("Forgot your password?").click();
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("013 - Verify 'Forgot your password?' link navigates to the Password Reset page", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
  await page.getByText("Forgot your password?").click();
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page.locator("input[name=\"username\"]")).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("requestPasswordResetCode"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("014 - Verify direct deep-link to a protected page without a session redirects to Login", async ({ page }) => {
  await page.goto("/web/index.php/dashboard/index");
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("015 - Verify Logout terminates the session and browser Back does not restore the Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("dashboard/index"), { timeout: 15000 });
  await page.locator("span.oxd-userdropdown-tab").click();
  await page.getByText("Logout", { exact: true }).click();
  await page.locator("body").press("Alt+ArrowLeft");
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("auth/login"), { timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
});
